---
title: "DoRoThEA notebook"
output: html_notebook
---


```{r}

library(dplyr)
library(viper)
library(dorothea)
data(bcellViper, package = "bcellViper")
data(dorothea_hs, package = "dorothea")
mat_toy <- dset@assayData$exprs

setwd('~/gitHub/panacea_indra/other/cosmos/')
cfa_df <- read.csv('~/gitHub/panacea_indra/other/cosmos/Data/Proteomics/CFA_panacea_unprocessed_16plex_data.csv', header = T)

mart_table <- read.table('./input/mart_export.txt', sep='\t', header = T)
colnames(mart_table) <- c('HGNC_ID', 'HGNC_SYMBOL', 'MOUSE_SYMBOL', 'MOUSE_ID')
# Removing rows with no value
mart_table <- mart_table[Reduce(`&`, lapply(mart_table, function(x) !x=="")),]


cfa_df <- cfa_df[!duplicated(cfa_df$X), ]
colnames(cfa_df)[1] <- 'MOUSE_SYMBOL'
cfa_df_merged <- merge(cfa_df, mart_table[,c(2,3)], by='MOUSE_SYMBOL')
cfa_df_merged$MOUSE_SYMBOL <- NULL
cfa_df_merged <- cfa_df_merged[!duplicated(cfa_df_merged$HGNC_SYMBOL), ]
mat <- cfa_df_merged
rownames(mat) <- cfa_df_merged$HGNC_SYMBOL
mat$HGNC_SYMBOL <- NULL
mat <- mat[, c(1,2,3)]


#cfa_df1 <- data.frame(row.names = cfa_df$X, 'FoldChange'=cfa_df$fold.change)

```

```{r "run viper", message=FALSE}
regulons = dorothea_hs %>%
  filter(confidence %in% c("A", "B"))
tf_activities <- run_viper(mat, regulons, 
                           options =  list(method = "scale", minsize = 4, 
                                           eset.filter = FALSE, cores = 1, 
                                           verbose = FALSE))

write.csv
```